spring:
  cloud:
    gateway:
      routes:
        - id: customer-route
          uri: http://localhost:8081
          predicates:
            - Path=/v1/customer/**
        - id: auth-route
          uri: http://localhost:8082
          predicates:
            - Path=/v1/user-registration/**
        - id: order-route
          uri: http://localhost:8083
          predicates:
            - Path=/v1/order/**
    security:
      oauth2:
        resourceserver:
          jwt:
            jwk-set-uri: "http://localhost:8082/v1/user-registration/jwks.json"
  main:
    web-application-type: reactive